#!/usr/bin/perl
use warnings;
use strict;
use utf8;

{
    package AmazonRemoteControlServer;

    # put your keyboard input here
    my $device = '/dev/input/event4';

    use HTTP::Server::Simple::CGI;
    use base qw(HTTP::Server::Simple::CGI);

    sub handle_request {
        my $self = shift;
        my $cgi  = shift;

        print "HTTP/1.0 200 OK\r\n";
        return unless ref $cgi;

        print q!Content-type:text/html;charset:utf-8;

<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    .centered {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
    td{
        width:5rem;
        height:5rem;
    }
    button{
        width:100%;
        padding:5rem;
        font-size:2rem;
        cursor:pointer;
        background:blue;
        color:white;
        border-radius:5rem;
    }
</style>
<script>
    function call(key){
        fetch('/?key='+key);
    }
</script>
<body>
<div class="centered">
    <table>
    <tr>
        <td></td>
        <td><button onclick="call('UP')">volume<br>up</button></td>
        <td></td>
    </tr>
    <tr>
        <td><button onclick="call('LEFT')">&lt;&lt;</button></td>
        <td><button onclick="call('SPACE')">pause<br>start</button></td>
        <td><button onclick="call('RIGHT')">&gt;&gt;</button></td>
    </tr>
    <tr>
        <td></td>
        <td><button onclick="call('DOWN')">volume<br>down</button></td>
        <td></td>
    </tr>
</div>
</body>
</html>
!;

        if ( my $key = $cgi->param('key') ) {
            next unless $key=~/^(LEFT|RIGHT|UP|DOWN|SPACE)$/;
            system qq{evemu-event $device --type EV_KEY --code KEY_$key --value 1 --sync};
            system qq{evemu-event $device --type EV_KEY --code KEY_$key --value 0 --sync};
        }
    }
}

AmazonRemoteControlServer->new(8080)->run();
