#!/usr/bin/perl
use warnings;
use strict;
use utf8;

{
    package AmazonRemoteControlServer;

    # put your keyboard input here
    my $device = '/dev/input/event4';

    use HTTP::Server::Simple::CGI;
    use base qw(HTTP::Server::Simple::CGI);

    sub handle_request {
        my $self = shift;
        my $cgi  = shift;

        print "HTTP/1.0 200 OK\r\n";
        return unless ref $cgi;

        print q!Content-type:text/html;charset:utf-8;

<html>
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<style>
    *{
        border:0;
        padding:0;
        background:#001;
    }
    .centered {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
    table{
        width:100vmin;
        height:100vmin;
    }
    td{
        width:25vmin;
        height:25vmin;
        text-align:center;
    }
    button:hover{
        background:#11f;
        border:        1vmin solid #00f;
        border-bottom: 1vmin solid #006;
        border-right:  1vmin solid #006;
    }
    button{
        margin:2vmin;
        width:66%;
        height:66%;
        font-size:5vmin;
        cursor:pointer;
        background:#ccc;
        color:white;
        border-radius:5vmin;
        border: 1vmin solid #006;
        border-bottom: 1vmin solid #003;
        border-right:  1vmin solid #003;
        transition: all 1s;
    }
</style>
<script>
    function call(key){
        fetch('/?key='+key);
        window.navigator.vibrate(200);
    }
</script>
<body>
<div class="centered">
    <table>
    <tr>
        <td></td>
        <td><button onclick="call('UP')">Vol. +</button></td>
        <td></td>
    </tr>
    <tr>
        <td><button onclick="call('LEFT')">&lt;&lt;</button></td>
        <td><button onclick="call('SPACE')">&#x25b6; / ||</button></td>
        <td><button onclick="call('RIGHT')">&gt;&gt;</button></td>
    </tr>
    <tr>
        <td></td>
        <td><button onclick="call('DOWN')">Vol. -</button></td>
        <td></td>
    </tr>
</div>
</body>
</html>
!;

        if ( my $key = $cgi->param('key') ) {
            next unless $key=~/^(LEFT|RIGHT|UP|DOWN|SPACE)$/;
            system qq{evemu-event $device --type EV_KEY --code KEY_$key --value 1 --sync};
            system qq{evemu-event $device --type EV_KEY --code KEY_$key --value 0 --sync};
        }
    }
}

AmazonRemoteControlServer->new(8080)->run();
